`timescale 1ns / 1ps

/* THIS IS CODE GENERATED BY CLAUDE AI THAT HAS BEEN MODIFIED
*/

module L1_tb #(
    parameter L1_capacity = 8,
    parameter L2_capacity = 120,
    parameter timestamp_bits = 32,
    parameter orderID_bits = 16,
    parameter price_bits = 16,
    parameter qty_bits = 16,
    parameter order_locations = 3,
    parameter FoB = 1,
    parameter order_width = order_locations + FoB + timestamp_bits + orderID_bits + price_bits + qty_bits,
    parameter num_incoming_orders = 5,
    parameter num_dut_orders = 100,
    parameter test_price = 100,
    parameter test_qty = 50
    )();

    logic clk, rstn, done_matching, L2_orders_ready;
    logic [$clog2(L1_capacity + L2_capacity)-1:0] top_level_tail_ptr;
    logic [$clog2(num_incoming_orders*2)-1:0] num_orders_added;
    logic [$clog2(num_incoming_orders*2)-1:0] num_orders_removed;
    logic [$clog2(num_incoming_orders)-1:0] num_cancelled;
    logic [$clog2(L1_capacity+L2_capacity)-1:0] cancelled_orders [num_incoming_orders];
    logic [order_width-1:0] new_orders [num_incoming_orders*2];
    logic [order_width-5:0] L2_orders [num_incoming_orders];
    logic [order_width-5:0] evicted_orders [num_incoming_orders];
    logic L1_sorted;

    // Stored evicted orders to use as L2_orders in later tests
    logic [order_width-1:0] L2_sim [16];
    logic [3:0] L2_sim_ptr;

    L1 #(
        .L1_capacity(L1_capacity),
        .L2_capacity(L2_capacity),
        .timestamp_bits(timestamp_bits),
        .orderID_bits(orderID_bits),
        .price_bits(price_bits),
        .qty_bits(qty_bits),
        .order_locations(order_locations),
        .FoB(FoB),
        .num_incoming_orders(num_incoming_orders)
    ) DUT (
        .clk(clk),
        .rstn(rstn),
        .done_matching(done_matching),
        .L2_orders_ready(L2_orders_ready),
        .top_level_tail_ptr(top_level_tail_ptr),
        .num_orders_added(num_orders_added),
        .num_orders_removed(num_orders_removed),
        .num_cancelled(num_cancelled),
        .cancelled_orders(cancelled_orders),
        .new_orders(new_orders),
        .L2_orders(L2_orders),
        .evicted_orders(evicted_orders),
        .L1_sorted(L1_sorted)
    );

    // Clock generation: 10ns period
    initial clk = 0;
    always #5 clk = ~clk;

    // -------------------------------------------------------------------------
    // Order generation helpers
    // order format (MSB to LSB):
    //   [order_width-1 -: 3] = location (3'b001 = L1)
    //   [order_width-4]      = FoB (1 = front, 0 = back)
    //   [timestamp_bits]     = timestamp
    //   [orderID_bits]       = order ID
    //   [price_bits]         = price
    //   [qty_bits]           = qty
    // -------------------------------------------------------------------------
    function automatic logic [order_width-1:0] make_order(
        input logic [2:0]               loc,
        input logic                     fob,
        input logic [timestamp_bits-1:0] ts,
        input logic [orderID_bits-1:0]  oid,
        input logic [price_bits-1:0]    price,
        input logic [qty_bits-1:0]      qty
    );
        make_order = {loc, fob, ts, oid, price, qty};
    endfunction

    // Generate a price with small random offset around test_price (+/- 10)
    function automatic logic [price_bits-1:0] rand_price();
        rand_price = test_price + ($urandom_range(0,20) - 10);
    endfunction

    // Generate a qty with small random offset around test_qty (+/- 10)
    function automatic logic [qty_bits-1:0] rand_qty();
        rand_qty = test_qty + ($urandom_range(0,20) - 10);
    endfunction

    // Pre-generated order pool: timestamps increment every 2 orders,
    // majority front insertions (FoB=1), occasional back (FoB=0)
    logic [order_width-1:0] dut_new_orders [num_dut_orders];
    initial begin
        for(int i = 0; i < num_dut_orders; i++) begin
            dut_new_orders[i] = make_order(
                3'b001,                     // L1 location
                ((i % 5 != 4) || (i > L1_capacity)) ? 1'b1 : 1'b0, // Every 5th order goes to back
                i / 2,                      // Timestamp increases every 2 orders
                i[orderID_bits-1:0],        // Order ID = index
                rand_price(),
                rand_qty()
            );
        end
    end

    // L2_orders pool: location bits stripped (order_width-5 wide)
    logic [order_width-5:0] l2_order_pool [num_dut_orders];
    initial begin
        logic [timestamp_bits-1:0] ts;
        logic [orderID_bits-1:0]   oid;
        for(int i = 0; i < num_dut_orders; i++) begin
            ts  = timestamp_bits'(i / 2);
            oid = orderID_bits'(i + num_dut_orders);
            l2_order_pool[i] = {ts, oid, rand_price(), rand_qty()};
        end
    end
    
    // Fill stored_evicted so we can reuse
    int n;
    always_ff @(posedge clk) begin
        for(n = 0; n < num_incoming_orders; n++) begin
            if(evicted_orders[n] > 0) begin // Check valid
                L2_sim[L2_sim_ptr] = evicted_orders[n];
                L2_sim_ptr = L2_sim_ptr + 1;
            end
        end
    end

    // -------------------------------------------------------------------------
    // Task: reset DUT
    // -------------------------------------------------------------------------
    task do_reset();
        rstn            = 0;
        done_matching   = 0;
        L2_orders_ready = 0;
        top_level_tail_ptr = 0;
        num_orders_added   = 0;
        num_orders_removed = 0;
        num_cancelled      = 0;
        L2_sim_ptr = 0;
        for(int i = 0; i < num_incoming_orders; i++) begin
            cancelled_orders[i] = 0;
            new_orders[i*2]     = 0;
            new_orders[i*2+1]   = 0;
            L2_orders[i]        = 0;
        end
        for(int j = 0; j < 20; j++) begin
            L2_sim[j] = 0;
        end
        @(posedge clk); #1;
        rstn = 1;
        done_matching   = 1;
        @(posedge clk); #1;
    endtask

    // Normal conditions
    task send_orders(
        input logic [order_width-1:0] ord0,
        input logic [order_width-1:0] ord1,
        input logic [order_width-1:0] ord2,
        input logic [order_width-1:0] ord3,
        input logic [order_width-1:0] ord4,
        input logic [$clog2(L1_capacity+L2_capacity)-1:0] tail_ptr,
        input logic [$clog2(num_incoming_orders*2)-1:0] n_added,
        input logic [$clog2(num_incoming_orders*2)-1:0] n_removed
    );
        new_orders[0]      = ord0;
        new_orders[1]      = ord1;
        new_orders[2]      = ord2;
        new_orders[3]      = ord3;
        new_orders[4]      = ord4;
        top_level_tail_ptr = tail_ptr;
        num_orders_added   = n_added;
        num_orders_removed = n_removed;
        done_matching      = 1;
        L2_orders_ready    = 1;
        @(posedge clk); #1;    
        done_matching   = 0;
        L2_orders_ready = 0;
    endtask
    
    // Cause low overflow
    task send_orders_ofl1(
        input logic [order_width-1:0] ord0,
        input logic [order_width-1:0] ord1,
        input logic [order_width-1:0] ord2,
        input logic [order_width-1:0] ord3,
        input logic [order_width-1:0] ord4,
        input logic [order_width-1:0] ord5,
        input logic [$clog2(L1_capacity+L2_capacity)-1:0] tail_ptr,
        input logic [$clog2(num_incoming_orders*2)-1:0] n_added,
        input logic [$clog2(num_incoming_orders*2)-1:0] n_removed
    );
        new_orders[0]      = ord0;
        new_orders[1]      = ord1;
        new_orders[2]      = ord2;
        new_orders[3]      = ord3;
        new_orders[4]      = ord4;
        new_orders[5]      = ord5;
        top_level_tail_ptr = tail_ptr;
        num_orders_added   = n_added;
        num_orders_removed = n_removed;
        done_matching      = 1;
        L2_orders_ready    = 1;
        @(posedge clk); #1;   
        done_matching   = 0;
        L2_orders_ready = 0;
    endtask
    
    // Large overflow
    task send_orders_ofl2(
        input logic [order_width-1:0] ord0,
        input logic [order_width-1:0] ord1,
        input logic [order_width-1:0] ord2,
        input logic [order_width-1:0] ord3,
        input logic [order_width-1:0] ord4,
        input logic [order_width-1:0] ord5,
        input logic [order_width-1:0] ord6,
        input logic [$clog2(L1_capacity+L2_capacity)-1:0] tail_ptr,
        input logic [$clog2(num_incoming_orders*2)-1:0] n_added,
        input logic [$clog2(num_incoming_orders*2)-1:0] n_removed
    );
        new_orders[0]      = ord0;
        new_orders[1]      = ord1;
        new_orders[2]      = ord2;
        new_orders[3]      = ord3;
        new_orders[4]      = ord4;
        new_orders[5]      = ord5;
        new_orders[6]      = ord6;
        top_level_tail_ptr = tail_ptr;
        num_orders_added   = n_added;
        num_orders_removed = n_removed;
        done_matching      = 1;
        L2_orders_ready    = 1;
        @(posedge clk); #1;   
        done_matching   = 0;
        L2_orders_ready = 0;
    endtask
    
    task send_orders_removal1(
        input logic [order_width-1:0] ord0,
        input logic [order_width-1:0] ord1,
        input logic [order_width-1:0] ord2,
        input logic [order_width-1:0] ord3,
        input logic [$clog2(L1_capacity+L2_capacity)-1:0] tail_ptr,
        input logic [$clog2(num_incoming_orders*2)-1:0] n_added,
        input logic [$clog2(num_incoming_orders*2)-1:0] n_removed
    );
        new_orders[0]      = ord0;
        new_orders[1]      = ord1;
        new_orders[2]      = ord2;
        new_orders[3]      = ord3;
        top_level_tail_ptr = tail_ptr;
        num_orders_added   = n_added;
        num_orders_removed = n_removed;
        done_matching      = 1;
        L2_orders_ready    = 1;
        @(posedge clk); #1;    
        done_matching   = 0;
        L2_orders_ready = 0;
    endtask
    
    task send_orders_removal2(
        input logic [order_width-1:0] ord0,
        input logic [order_width-1:0] ord1,
        input logic [$clog2(L1_capacity+L2_capacity)-1:0] tail_ptr,
        input logic [$clog2(num_incoming_orders*2)-1:0] n_added,
        input logic [$clog2(num_incoming_orders*2)-1:0] n_removed
    );
        new_orders[0]      = ord0;
        new_orders[1]      = ord1;
        top_level_tail_ptr = tail_ptr;
        num_orders_added   = n_added;
        num_orders_removed = n_removed;
        done_matching      = 1;
        L2_orders_ready    = 1;
        @(posedge clk); #1;    
        done_matching   = 0;
        L2_orders_ready = 0;
    endtask

    // -------------------------------------------------------------------------
    // Test 1: No cancellations, no insertions or removals, push front and back : GOOD
    // -------------------------------------------------------------------------
    task test1();
        $display("=== Test 1: Simple front population, check L1_sorted ===");
        do_reset();
        num_cancelled = 0;
        for(int i = 0; i < 8; i++) begin
            send_orders(dut_new_orders[i*5], dut_new_orders[i*5+1], dut_new_orders[i*5+2], dut_new_orders[i*5+3], dut_new_orders[i*5+4], i+4, 0, 0);
        end
        @(posedge clk); #1;   
        @(posedge clk); #1;
        assert(L1_sorted) 
            else $error("Test 1 FAILED: L1_sorted not asserted after full population");
        $display("Test 1 PASSED");
    endtask

    // -------------------------------------------------------------------------
    // Test 2: Overflow with insertions, check evicted orders, small overflow
    // -------------------------------------------------------------------------
    task test2();
        $display("=== Test 2: Low overflow, check L1_sorted ===");
        do_reset();
        num_cancelled = 0;
        for(int i = 0; i < L1_capacity; i++) begin
            send_orders_ofl1(dut_new_orders[i*6], dut_new_orders[i*6+1], dut_new_orders[i*6+2], dut_new_orders[i*6+3], dut_new_orders[i*6+4], dut_new_orders[i*6+5], i+5, !(!i), 0);
        end
        @(posedge clk); #1;   
        @(posedge clk); #1;
        $display("Test 2 PASSED: evicted_orders[0] = %0h", evicted_orders[0]);
    endtask

    // -------------------------------------------------------------------------
    // Test 3: Overflow with insertions, check evicted orders, large overflow
    // -------------------------------------------------------------------------
    task test3();
        $display("=== Test 3: Large overflow, check L1_sorted ===");
        do_reset();
        num_cancelled = 0;
        for(int i = 0; i < L1_capacity; i++) begin
            send_orders_ofl2(dut_new_orders[i*7], dut_new_orders[i*7+1], dut_new_orders[i*7+2], dut_new_orders[i*7+3], dut_new_orders[i*7+4], dut_new_orders[i*7+5], dut_new_orders[i*7+6], i+5, 1+!(!i), 0);
        end
        @(posedge clk); #1;   
        @(posedge clk); #1;
        $display("Test 2 PASSED: evicted_orders[0] = %0h", evicted_orders[0]);
    endtask
    

    // -------------------------------------------------------------------------
    // Test 4: Simple cancellation, no overflow, only 1
    // -------------------------------------------------------------------------
    task test4();
        $display("=== Test 4: 1 cancellation ===");
        do_reset();
        // Partially fill L1
        for(int i = 0; i < L1_capacity/2; i++) begin
            send_orders(dut_new_orders[i*5], dut_new_orders[i*5+1], dut_new_orders[i*5+2], dut_new_orders[i*5+3], dut_new_orders[i*5+4], !(!i)+4, 0, 0);
        end
        // Cancel order 1
        num_cancelled      = 1;
        cancelled_orders[0] = 1;
        L2_orders[0]       = l2_order_pool[0];
        L2_orders_ready    = 1;
        done_matching      = 0;
        @(posedge clk); #1;
        L2_orders_ready = 0;
        num_cancelled   = 0;
        @(posedge clk); #1;
        // Continue filling
        for(int i = L1_capacity/2; i < L1_capacity; i++) begin
            send_orders(dut_new_orders[i*5], dut_new_orders[i*5+1], dut_new_orders[i*5+2], dut_new_orders[i*5+3], dut_new_orders[i*5+4], 5, 0, 0);
        end
        assert(L1_sorted)
            else $error("Test 5 FAILED: L1_sorted not asserted after cancellation + fill");
        $display("Test 5 PASSED");
    endtask

    // -------------------------------------------------------------------------
    // Test 5: Multiple cancellations, no overflow
    // -------------------------------------------------------------------------
    task test5();
        $display("=== Test 5: Multiple Cancellations ===");
        do_reset();
        // Partially fill L1
        for(int i = 0; i < L1_capacity/2; i++) begin
            send_orders(dut_new_orders[i*5], dut_new_orders[i*5+1], dut_new_orders[i*5+2], dut_new_orders[i*5+3], dut_new_orders[i*5+4], !(!i)+4, 0, 0);
        end
        // Cancel order 1
        num_cancelled      = 3;
        cancelled_orders[0] = 0;
        cancelled_orders[1] = 2;
        cancelled_orders[2] = 4;
        L2_orders[0]       = l2_order_pool[0];
        L2_orders[1]       = l2_order_pool[1];
        L2_orders[2]       = l2_order_pool[2];
        L2_orders_ready    = 1;
        done_matching      = 0;
        @(posedge clk); #1;
        L2_orders_ready = 0;
        num_cancelled   = 0;
        @(posedge clk); #1;
        // Continue filling
        for(int i = L1_capacity/2; i < L1_capacity; i++) begin
            send_orders(dut_new_orders[i*5], dut_new_orders[i*5+1], dut_new_orders[i*5+2], dut_new_orders[i*5+3], dut_new_orders[i*5+4], 5, 0, 0);
        end
        assert(L1_sorted)
            else $error("Test 5 FAILED: L1_sorted not asserted after cancellation + fill");
        $display("Test 5 PASSED");
    endtask

    // -------------------------------------------------------------------------
    // Test 6: Multiple, repeated cancellations
    // -------------------------------------------------------------------------
    task test6();
        $display("=== Test 5: Multiple Cancellations ===");
        do_reset();
        // Partially fill L1
        for(int i = 0; i < L1_capacity/2; i++) begin
            send_orders(dut_new_orders[i*5], dut_new_orders[i*5+1], dut_new_orders[i*5+2], dut_new_orders[i*5+3], dut_new_orders[i*5+4], !(!i)+4, 0, 0);
        end
        // Cancel order, first set
        num_cancelled      = 3;
        cancelled_orders[0] = 0;
        cancelled_orders[1] = 2;
        cancelled_orders[2] = 4;
        L2_orders[0]       = l2_order_pool[0];
        L2_orders[1]       = l2_order_pool[1];
        L2_orders[2]       = l2_order_pool[2];
        L2_orders_ready    = 1;
        done_matching      = 0;
        @(posedge clk); #1;
        L2_orders_ready = 1;
        num_cancelled      = 2;
        cancelled_orders[0] = 0;
        cancelled_orders[1] = 1;
        cancelled_orders[2] = 0;
        L2_orders[0]       = l2_order_pool[0];
        L2_orders[1]       = l2_order_pool[1];
        done_matching      = 0;
        @(posedge clk); #1;
        // Continue filling
        for(int i = L1_capacity/2; i < L1_capacity; i++) begin
            send_orders(dut_new_orders[i*5], dut_new_orders[i*5+1], dut_new_orders[i*5+2], dut_new_orders[i*5+3], dut_new_orders[i*5+4], 5, 0, 0);
        end
        assert(L1_sorted)
            else $error("Test 5 FAILED: L1_sorted not asserted after cancellation + fill");
        $display("Test 5 PASSED");
    endtask
    
    // -------------------------------------------------------------------------
    // Test 7: Overflow with cancellations
    // -------------------------------------------------------------------------
    task test7();
        $display("=== Test 7: Cancellations with overflow ===");
        do_reset();
        // Partially fill L1
        for(int i = 0; i < L1_capacity/2; i++) begin
            send_orders_ofl1(dut_new_orders[i*6], dut_new_orders[i*6+1], dut_new_orders[i*6+2], dut_new_orders[i*6+3], dut_new_orders[i*6+4], dut_new_orders[i*6+5], i+5, !(!i), 0);
        end
        // Cancel order, first set
        L2_orders[0]       = l2_order_pool[0];
        num_cancelled      = 1;
        cancelled_orders[0] = 0;
        L2_orders_ready    = 1;
        done_matching      = 0;
        @(posedge clk); #1;
        L2_orders_ready = 1;
        num_cancelled      = 1;
        cancelled_orders[0] = 3;
        L2_orders[0]       = l2_order_pool[1];
        done_matching      = 0;
        @(posedge clk); #1;
        // Continue filling
        for(int i = L1_capacity/2; i < L1_capacity; i++) begin
            send_orders_ofl1(dut_new_orders[i*6], dut_new_orders[i*6+1], dut_new_orders[i*6+2], dut_new_orders[i*6+3], dut_new_orders[i*6+4], dut_new_orders[i*6+5], i+5, 1, 0);
        end
        assert(L1_sorted)
            else $error("Test 5 FAILED: L1_sorted not asserted after cancellation + fill");
        $display("Test 5 PASSED");
    endtask
    
    // -------------------------------------------------------------------------
    // Test 8: Overflow with mutliple cancellations
    // -------------------------------------------------------------------------
    task test8();
        $display("=== Test 8: Multiple cancellations with overflow ===");
        do_reset();
        // Partially fill L1
        for(int i = 0; i < L1_capacity/2; i++) begin
            send_orders_ofl1(dut_new_orders[i*6], dut_new_orders[i*6+1], dut_new_orders[i*6+2], dut_new_orders[i*6+3], dut_new_orders[i*6+4], dut_new_orders[i*6+5], i+5, !(!i), 0);
        end
        // Cancel order, first set
        num_cancelled      = 3;
        cancelled_orders[0] = 0;
        cancelled_orders[1] = 2;
        cancelled_orders[2] = 4;
        L2_orders[0]       = l2_order_pool[0];
        L2_orders[1]       = l2_order_pool[1];
        L2_orders[2]       = l2_order_pool[2];
        L2_orders_ready    = 1;
        done_matching      = 0;
        @(posedge clk); #1;
        L2_orders_ready = 1;
        num_cancelled      = 2;
        cancelled_orders[0] = 0;
        cancelled_orders[1] = 1;
        cancelled_orders[2] = 0;
        L2_orders[0]       = l2_order_pool[0];
        L2_orders[1]       = l2_order_pool[1];
        done_matching      = 0;
        @(posedge clk); #1;
        // Continue filling
        for(int i = L1_capacity/2; i < L1_capacity; i++) begin
            send_orders_ofl1(dut_new_orders[i*6], dut_new_orders[i*6+1], dut_new_orders[i*6+2], dut_new_orders[i*6+3], dut_new_orders[i*6+4], dut_new_orders[i*6+5], i+5, 1, 0);
        end
        assert(L1_sorted)
            else $error("Test 5 FAILED: L1_sorted not asserted after cancellation + fill");
        $display("Test 5 PASSED");
    endtask
    
    // -------------------------------------------------------------------------
    // Test 9: 1 Removal via matching
    // -------------------------------------------------------------------------
    task test9();
        $display("=== Test 9: 1 removal ===");
        do_reset();
        num_cancelled = 0;
        for(int i = 0; i < L1_capacity; i++) begin
            send_orders_ofl1(dut_new_orders[i*6], dut_new_orders[i*6+1], dut_new_orders[i*6+2], dut_new_orders[i*6+3], dut_new_orders[i*6+4], dut_new_orders[i*6+5], i+5, !(!i), 0);
        end
        send_orders_removal1(dut_new_orders[L1_capacity*6], dut_new_orders[L1_capacity*6+1], dut_new_orders[L1_capacity*6+2], dut_new_orders[L1_capacity*6+3], 13, 0, 1);
        @(posedge clk); #1;   
        @(posedge clk); #1;
    endtask
    
    // -------------------------------------------------------------------------
    // Test 10: Multiple Removal via matching
    // -------------------------------------------------------------------------
    task test10();
        $display("=== Test 10: Multiple removal ===");
        do_reset();
        num_cancelled = 0;
        for(int i = 0; i < L1_capacity; i++) begin
            send_orders_ofl1(dut_new_orders[i*6], dut_new_orders[i*6+1], dut_new_orders[i*6+2], dut_new_orders[i*6+3], dut_new_orders[i*6+4], dut_new_orders[i*6+5], i+5, !(!i), 0);
        end
        send_orders_removal2(dut_new_orders[L1_capacity*6], dut_new_orders[L1_capacity*6+1], 13, 0, 3);
        @(posedge clk); #1;   
        @(posedge clk); #1;
    endtask
    
    // Test 11 : Low stress test, mix of adding, cancels, and removals
    // -------------------------------------------------------------------------
    task test11();
        $display("=== Test 11: Low stress mix of adds, cancels, removals ===");
        do_reset();
        num_cancelled = 0;
    
        // Phase 1: Partially fill L1 with front insertions (4 cycles)
        for(int i = 0; i < L1_capacity/2; i++) begin
            send_orders(
                dut_new_orders[i*5], dut_new_orders[i*5+1],
                dut_new_orders[i*5+2], dut_new_orders[i*5+3],
                dut_new_orders[i*5+4],
                4, 0, 0
            );
        end
    
        // Phase 2: Cancel 1 order, replace with L2
        num_cancelled       = 1;
        cancelled_orders[0] = 2;
        L2_orders[0]        = l2_order_pool[0];
        L2_orders_ready     = 1;
        done_matching       = 0;
        @(posedge clk); #1;
        L2_orders_ready = 0;
        num_cancelled   = 0;
    
        // Phase 3: Fill remainder with mild overflow (1 eviction per cycle)
        for(int i = L1_capacity/2; i < L1_capacity; i++) begin
            send_orders_ofl1(
                dut_new_orders[i*6], dut_new_orders[i*6+1],
                dut_new_orders[i*6+2], dut_new_orders[i*6+3],
                dut_new_orders[i*6+4], dut_new_orders[i*6+5],
                4 + (i - L1_capacity/2), 1, 0
            );
        end
    
        // Phase 4: Cancel 2 more orders simultaneously, replace with L2
        num_cancelled       = 2;
        cancelled_orders[0] = 1;
        cancelled_orders[1] = 3;
        L2_orders[0]        = l2_order_pool[1];
        L2_orders[1]        = l2_order_pool[2];
        L2_orders_ready     = 1;
        done_matching       = 0;
        @(posedge clk); #1;
        L2_orders_ready = 0;
        num_cancelled   = 0;
    
        // Phase 5: Add new orders with 1 removal (simulate a partial match)
        L2_orders[0]    = l2_order_pool[3];
        L2_orders_ready = 1;
        send_orders_removal1(
            dut_new_orders[L1_capacity*5],   dut_new_orders[L1_capacity*5+1],
            dut_new_orders[L1_capacity*5+2], dut_new_orders[L1_capacity*5+3],
            L1_capacity+4, 0, 1
        );
        @(posedge clk); #1;
        L2_orders_ready = 0;
    
        // Phase 6: Final removal of 2 matched orders, fill from L2
        L2_orders[0]    = l2_order_pool[5];
        L2_orders[1]    = l2_order_pool[6];
        L2_orders_ready = 1;
        send_orders_removal2(
            dut_new_orders[L1_capacity*5+6], dut_new_orders[L1_capacity*5+7],
            L1_capacity+4, 0, 2
        );
        @(posedge clk); #1;
        L2_orders_ready = 0;
        @(posedge clk); #1;
    
    endtask
    
    // -------------------------------------------------------------------------
    // Run all tests
    // -------------------------------------------------------------------------
    initial begin
//        test1();
//        test2();
//        test3();
//        test4();
//        test5();
//        test6();
//        test7();
//        test8();
//        test9();
        test10();
//        test11();
        $display("=== All tests complete ===");
        $finish;
    end

endmodule
